// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wecstqyokwmungksiuiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlY3N0cXlva3dtdW5na3NpdWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxOTE3MDgsImV4cCI6MjA1Mzc2NzcwOH0.-xjne0miTvwGpJsA7yjDK-KTAQPJnLovlxfP6hM0lak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);